# Generated by Django 5.1.1 on 2024-11-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_chatmessage_receiver_alter_chatmessage_sender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="image",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="chat_images"
            ),
        ),
    ]
