# Generated by Django 5.1.1 on 2024-11-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_chatmessage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="image",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="chat_images"
            ),
        ),
    ]
