# Generated by Django 5.1.1 on 2024-11-05 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_chatmessage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="friend_requests_sent",
            field=models.ManyToManyField(
                related_name="friend_requests_received", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(
                related_name="friends_with", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
