# Generated by Django 5.1.1 on 2024-11-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_user_friend_requests_sent_user_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="status_online",
            field=models.CharField(default="offline", max_length=50),
        ),
    ]
