# Generated by Django 5.1.1 on 2024-11-07 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_roomchat_chatmessage_room_chat_id_friendship_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="friends",
        ),
    ]
