# Generated by Django 5.1.1 on 2024-11-07 02:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_roomchat_remove_user_friends_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(
                related_name="friend_of",
                through="api.Friendship",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
