# Generated by Django 5.1.1 on 2024-11-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_user_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_language",
            field=models.CharField(default="en", max_length=2),
        ),
    ]
