# Generated by Django 5.1.1 on 2024-11-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_user_user_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="message_translated",
            field=models.TextField(default=models.TextField()),
        ),
    ]
