# Generated by Django 5.1.1 on 2024-11-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_chatmessage_message_translated"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="hobbies",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
