# Generated by Django 5.1.1 on 2024-11-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_profile_address_profile_hobbies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="message_translated",
            field=models.TextField(default=""),
        ),
    ]
